### ISSUE TITLE
brew list fails due to using Puppet's Ruby

### ISSUE THREAD

**Issue by jaredledvina** [halyard/puppet-homebrew#11]
```
2018-12-23 23:13:48 glaurung STARTING RUN
2018-12-23 23:13:57 glaurung Notice: Compiled catalog for glaurung.dathouse in environment production in 0.78 seconds
2018-12-23 23:13:58 glaurung Error: Failed to apply catalog: Execution of '/opt/brew/bin/brew list --full-name' returned 1: /opt/puppetlabs/puppet/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- active_support/core_ext/object/blank (LoadError)
2018-12-23 23:13:58 glaurung 	from /opt/puppetlabs/puppet/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
2018-12-23 23:13:58 glaurung 	from /opt/brew/Library/Homebrew/global.rb:10:in `<top (required)>'
2018-12-23 23:13:58 glaurung 	from /opt/brew/Library/Homebrew/brew.rb:13:in `require_relative'
2018-12-23 23:13:58 glaurung 	from /opt/brew/Library/Homebrew/brew.rb:13:in `<main>'
```

Works normally though:
```
glaurung:Downloads ghavil$ /opt/brew/bin/brew list
glaurung:Downloads ghavil$ 
```

**Comment by jaredledvina** [comment]
At least, this is my understanding of the error, I might be misreading it.

**Comment by jaredledvina** [comment]
hrrrm, I'm still looking at this but, I'm pretty lost, active_support is a dep of Homebrew it seems. However, I can't figure out how this works w/ the cli but fails when Puppet runs it.

**Comment by akerl** [comment]
Yea, this was an issue I hit for my Mojave install as well. It's something w/ how ruby picks the gem path (where it's using the right ruby but the wrong gems)
